### PR TITLE
Fix typo for `JWTError.signatureVerificationFailed` case

### PR DESCRIPTION
**Pull request by davdroman**
Succeeds #61 cause I had to re-fork in order to do further edits. Hope that's alright.

### CODE REVIEW

**Review by gwynne — APPROVED** [review]

**Comment by 0xTim** [comment]
Isn't the API breakage checker correct here? Anyone doing a switch will have a build error

**Comment by davdroman** [comment]
@0xTim oh yes, of course. Happy to drop it if it's a no-go.

**Comment by gwynne** [comment]
> Isn't the API breakage checker correct here? Anyone doing a switch will have a build error

Ouch, you're right, the compiler will still complain the switch isn't exhaustive 😞

**Comment by 0xTim** [comment]
Thanks for this @davdroman, thankfully we're working on a major update at the moment where this is already fixed

**Pull request closed without merging**
