### PR TITLE
Migrate HMAC to Crypto

### PR DESCRIPTION
**Pull request by 0xTim**
Migrate all the HMAC code away from BoringSSL to Swift Crypto (#24).

### CODE REVIEW

**Comment by 0xTim** [comment]
Changed the label as this is a SemVer-minor release (the existing APIs are all the same)

**Comment by 0xTim** [comment]
(For posterity)

Not sure if we should change the `Key: DataProtocol` to simply `[UInt8]` to remove a copy, but have left it how it was to preserve the public API.

CC @Lukasa if you'd like to take a look

**Comment by tanner0101** [comment]
> Changed the label as this is a SemVer-minor release (the existing APIs are all the same)

Oh good catch, I thought `HMACSigner<SHAType>` was public. This is minor semver 👍

**Comment by tanner0101** [comment]
These changes are now available in [4.0.0-rc.1.4](https://github.com/vapor/jwt-kit/releases/tag/4.0.0-rc.1.4)

**Comment by Lukasa** [comment]
Apologies for the late once-over, this looks totally fine to me.

**Pull request merged**
