### PR TITLE
Added JWK and JWKS support

### LINKED ISSUE #87: JWK Verification
Apparently the JWT 3 doesn't support JWK signing yet. This would be a good feature to implement, especially for those of us that used it in Vapor 2 🙂.

### PR DESCRIPTION
**Pull request by valeriomazzeo**
This pull request adds support for JWK and JWKS.
It fixes #87

Note: only RSA keys have been implemented so far.

### CODE REVIEW

**Comment by valeriomazzeo** [comment]
I have reverted that `master` merge. This is the PR as it was originally intended for Vapor 3 https://github.com/vapor/jwt-kit/pull/106 .

Just as a reminder I had already implemented this for Vapor 2, but for whatever reason it wasn't ported to Vapor 3.

It would be nice if you (@tanner0101) could please incorporate this feature also in the `master` branch, for Vapor 4. Otherwise I will have to re-implement it once again :(

**Comment by tanner0101** [comment]
@valeriomazzeo thanks for fixing the merge conflict. Sorry this PR has fallen through the cracks for so long. I'll add this feature to the master branch now 👍

**Comment by valeriomazzeo** [comment]
@tanner0101 @siemensikkema it seems this feature has not been ported to v4.

Please, tell me I don't have to re-implement this for the 3rd time ...

**Comment by 0xTim** [comment]
@valeriomazzeo JWKS support is definitely in there since it's used to verify the Sign In With Apple keys

**Comment by valeriomazzeo** [comment]
I have found the related files 🎉

I am now trying to figure out how to port this https://github.com/asensei/vapor-auth-jwt to Vapor 4 - still trying to understand what's redundant from there and what's not.

**Comment by valeriomazzeo** [comment]
@0xTim - so I think I got confused because the JWT signers are only local. So I couldn't find where the `JWKS` url was injected.

For my specific case, I think I'd have to implement an equivalent of `JWT+Apple.swift` in `JWT+JWKS.swift`.

It really looks like the standard JWT signers should be able to accept a generic JWKS url. I don't see any reason why not.

In my implementation I had a generic `JWTSignerRepository ` and all it needed was the JWKS url.

Thoughts?

**Comment by 0xTim** [comment]
@valeriomazzeo the Google and Apple JWKS code looks sufficiently duplicated to warrant something like that. Thoughts @gwynne ?

**Comment by gwynne** [comment]
Absolutely concur - the more generic our handling of data, the better, and we definitely have plenty of low-hanging fruit for de-duplication and additional supported things (key types, well-known token types, algorithms, you name it).

Most of the work in question probably belongs in https://github.com/vapor/jwt-kit, though, not just here.

**Comment by 0xTim** [comment]
Depends on if we want to add some `Client` knowledge to JWT-Kit

**Comment by gwynne** [comment]
I confess to an unforgivable ignorance of the topic 😆. Yeah, we definitely don't want to drag a Vapor dependency down below JWT, that defeats the purpose.

**Comment by valeriomazzeo** [comment]
@0xTim - by looking at the dependencies it seems that implement it in this repo makes more sense.

I also had a `cacheMinTTL` setting in [my implementation ](https://github.com/asensei/vapor-auth-jwt/blob/master/Sources/JWTAuth/Authentication/JWTExtensions/JWKSSignerRepository.swift).

It was then used by the [middleware](https://github.com/asensei/vapor-auth-jwt/blob/master/Sources/JWTAuth/Authentication/JWTAuthenticationMiddleware.swift) which where the signer repository was injected - I suppose that's now called `Authenticator`?

**Comment by 0xTim** [comment]
Yeah I think that's correct

**Pull request merged**
