### PR TITLE
Add support for Apple Silicon

### PR DESCRIPTION
**Pull request by 0xTim**
This PR adds support for Apple Silicon to JWTKit. I guess you'll have to take my word for it that the tests pass on that architecture! 😆 

It also updates the version of BoringSSL which we probably should have done a while ago

### CODE REVIEW

**Comment by 0xTim** [comment]
No idea why the tests are failing on one architecture

**Comment by jagreenwood** [comment]
Nice! I had assumed this package was using a custom built BoringSSL to remove support for iOS. Since this PR seeks to also add support for iOS, could it use BoringSSL supplied by swift-crypto as I did in this [fork](https://github.com/jagreenwood/jwt-kit)?

**Comment by 0xTim** [comment]
@jagreenwood I need to check the iOS support, but it was required to allow me to build the symbols for Apple Silicon as that option isn't available in Xcode at the moment. 

Having said that, what you're doing is technically wrong and risky. It's a bug in SwiftPM that you can see those symbols - you shouldn't be able to. If that gets patched, your code breaks and if BoringSSL gets updated (and as it has no stable ABI) then that may break for you as well

**Comment by tanner0101** [comment]
@0xTim nice! Could we do that BoringSSL upgrade as a separate PR? It's hard to see what the required changes are for arm specifically.

**Comment by 0xTim** [comment]
@tanner0101 sure

**Pull request closed without merging**
